
services:
  app:
    image: php:8.2-cli
    container_name: acme_widget_co_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php -v # Keeps the container running, or can be used to run scripts

  composer:
    image: composer:latest
    container_name: acme_widget_co_composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["composer"]
    # Example usage: docker-compose run --rm composer install
    # Example usage: docker-compose run --rm composer test
